import json
from pathlib import Path

raw_bytes = Path("worked_examples_trace.json").read_bytes()
raw = raw_bytes.decode("utf-16") if raw_bytes.startswith(b"\xff\xfe") else raw_bytes.decode("utf-8")
data = json.loads(raw[raw.index("["):])
out = ["# Medi Gaurd AI — Worked Synthetic Adjudication Traces", "", "These traces were generated by the current extraction and deterministic rule engine. Context values explicitly labeled as adjudication context are supplied to the rule engine; they are not claimed to have been extracted from the fixture.", ""]
for e in data:
    r = e["rule_engine_results"]
    out += [f"## Example {e['example']} — {e['title']}", "", f"**Bill fixture:** `{e['inputs']['bill']}`  ", f"**Policy fixture:** `{e['inputs']['policy']}`  ", f"**Bill pages:** {e['bill_pages']}  ", f"**Policy pages:** {e['policy_pages']}", "", "### Exact bill fields extracted", "", "| Field | Raw value | Confidence | Needs review | Evidence |", "|---|---|---:|---|---|"]
    for name, field in e["bill_raw_fields"].items():
        if field is None:
            out.append(f"| `{name}` | `<missing>` | — | — | — |")
        else:
            ev = "; ".join(f"{x['source_name']} page {x['page']} via {x['method']}" for x in field["evidence"])
            out.append(f"| `{name}` | `{field['value']}` | {field['confidence']:.2f}% | `{field['needs_review']}` | {ev or 'none'} |")
    out += ["", "### Exact policy values extracted", "", "| Term | Raw extracted value | Confidence | Source text/page |", "|---|---|---:|---|"]
    for name, term in e["policy_terms"].items():
        value = str(term.get("value"))
        source = term.get("source_text", "").replace("\n", " ")[:240]
        out.append(f"| `{name}` | `{value}` | {float(term.get('confidence', 0)):.2f} | `{source}` (page {term.get('source_page') or 'not assigned'}) |")
    out += ["", "### Adjudication context supplied to rules", "", "```json", json.dumps(e["inputs"]["context_not_extracted_from_fixture"], indent=2), "```", "", "### Rule order and exact outcome", "", "| Order | Rule | Outcome | Why |", "|---:|---|---|---|"]
    for i, item in enumerate(e["rule_order_and_trace"], 1):
        out.append(f"| {i} | `{item['rule']}` | **{item['outcome']}** | {item['why']} |")
    out += ["", "### Exact deterministic calculation trace", "", "| Rule ID | Status | Calculation | Amount | Warnings |", "|---|---|---|---:|---|"]
    for item in r["results"]:
        warnings = "; ".join(item.get("warnings", [])) or "none"
        amount = "—" if item.get("amount") is None else f"INR {float(item['amount']):,.2f}"
        out.append(f"| `{item['rule_id']}` | `{item['status']}` | `{item['calculation']}` | {amount} | {warnings} |")
    out += ["", f"**Covered amount:** INR {r['covered_amount']:,.2f}  ", f"**Deductible:** INR {r['deductible']:,.2f}  ", f"**Copayment:** INR {r['copayment']:,.2f}  ", f"**Payable amount:** INR {r['payable_amount']:,.2f}  ", f"**Final deterministic status:** **`{r['status']}`**", "", "### Decision chain", ""]
    for item in r.get("warnings", []):
        out.append(f"- `{item}`")
    if not r.get("warnings"):
        out.append("- No warnings or review conditions remained.")
    out.append("")
Path("WORKED_EXAMPLES_REPORT.md").write_text("\n".join(out), encoding="utf-8")
print("WORKED_EXAMPLES_REPORT_OK")
